    spring:
      data:
        mongodb.uri: mongodb+srv://${DB_USER}:${DB_PASSWORD}@webfluxcoursecluster.ikxhkhe.mongodb.net/${DB_NAME}?retryWrites=true&w=majority
      application: webflux-course\q